<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime\TripModifications;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripModifications.SelectedTrips</code>
 */
class SelectedTrips extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`. A `TripUpdate` with `schedule_relationship=REPLACEMENT` must not already exist for the trip.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     */
    private $trip_ids;
    /**
     * The ID of the new shape for the modified trips in this SelectedTrips. 
     * May refer to a new shape added using a `Shape` message in the same GTFS-RT feed, or to an existing shape defined in the GTFS-Static feed’s shapes.txt. 
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     *
     * Generated from protobuf field <code>optional string shape_id = 2;</code>
     */
    protected $shape_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $trip_ids
     *           A list of trips affected with this replacement that all have the same new `shape_id`. A `TripUpdate` with `schedule_relationship=REPLACEMENT` must not already exist for the trip.
     *     @type string $shape_id
     *           The ID of the new shape for the modified trips in this SelectedTrips. 
     *           May refer to a new shape added using a `Shape` message in the same GTFS-RT feed, or to an existing shape defined in the GTFS-Static feed’s shapes.txt. 
     *           If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`. A `TripUpdate` with `schedule_relationship=REPLACEMENT` must not already exist for the trip.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     * @return RepeatedField<string>
     */
    public function getTripIds()
    {
        return $this->trip_ids;
    }

    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`. A `TripUpdate` with `schedule_relationship=REPLACEMENT` must not already exist for the trip.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTripIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->trip_ids = $arr;

        return $this;
    }

    /**
     * The ID of the new shape for the modified trips in this SelectedTrips. 
     * May refer to a new shape added using a `Shape` message in the same GTFS-RT feed, or to an existing shape defined in the GTFS-Static feed’s shapes.txt. 
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     *
     * Generated from protobuf field <code>optional string shape_id = 2;</code>
     * @return string
     */
    public function getShapeId()
    {
        return isset($this->shape_id) ? $this->shape_id : '';
    }

    public function hasShapeId()
    {
        return isset($this->shape_id);
    }

    public function clearShapeId()
    {
        unset($this->shape_id);
    }

    /**
     * The ID of the new shape for the modified trips in this SelectedTrips. 
     * May refer to a new shape added using a `Shape` message in the same GTFS-RT feed, or to an existing shape defined in the GTFS-Static feed’s shapes.txt. 
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     *
     * Generated from protobuf field <code>optional string shape_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShapeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shape_id = $var;

        return $this;
    }

}

