<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An alert, indicating some sort of incident in the public transit network.
 *
 * Generated from protobuf message <code>transit_realtime.Alert</code>
 */
class Alert extends \Google\Protobuf\Internal\Message
{
    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * Should not be used - for backwards-compatibility only.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange active_period = 1 [deprecated = true];</code>
     * @deprecated
     */
    private $active_period;
    /**
     * Time when the alert should be shown to the user strictly for informative reasons.
     * If missing, the consuming application can decide when it's appropriate to be shown.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange communication_period = 2;</code>
     */
    private $communication_period;
    /**
     * Time when the services are affected by the alert. If communication_period is specified,
     * every time interval in impact_period must be fully contained within at least
     * one time interval of communication_period.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange impact_period = 3;</code>
     */
    private $impact_period;
    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    private $informed_entity;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Cause cause = 6;</code>
     */
    protected $cause = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Effect effect = 7;</code>
     */
    protected $effect = null;
    /**
     * The URL which provides additional information about the alert.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    protected $url = null;
    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    protected $header_text = null;
    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    protected $description_text = null;
    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
     */
    protected $tts_header_text = null;
    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
     */
    protected $tts_description_text = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.SeverityLevel severity_level = 14;</code>
     */
    protected $severity_level = null;
    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedImage image = 15;</code>
     */
    protected $image = null;
    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
     */
    protected $image_alternative_text = null;
    /**
     * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
     */
    protected $cause_detail = null;
    /**
     * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
     */
    protected $effect_detail = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Transit\Realtime\TimeRange[] $active_period
     *           Time when the alert should be shown to the user. If missing, the
     *           alert will be shown as long as it appears in the feed.
     *           If multiple ranges are given, the alert will be shown during all of them.
     *           Should not be used - for backwards-compatibility only.
     *     @type \Google\Transit\Realtime\TimeRange[] $communication_period
     *           Time when the alert should be shown to the user strictly for informative reasons.
     *           If missing, the consuming application can decide when it's appropriate to be shown.
     *           If multiple ranges are given, the alert will be shown during all of them.
     *     @type \Google\Transit\Realtime\TimeRange[] $impact_period
     *           Time when the services are affected by the alert. If communication_period is specified,
     *           every time interval in impact_period must be fully contained within at least
     *           one time interval of communication_period.
     *     @type \Google\Transit\Realtime\EntitySelector[] $informed_entity
     *           Entities whose users we should notify of this alert.
     *     @type int $cause
     *     @type int $effect
     *     @type \Google\Transit\Realtime\TranslatedString $url
     *           The URL which provides additional information about the alert.
     *     @type \Google\Transit\Realtime\TranslatedString $header_text
     *           Alert header. Contains a short summary of the alert text as plain-text.
     *     @type \Google\Transit\Realtime\TranslatedString $description_text
     *           Full description for the alert as plain-text. The information in the
     *           description should add to the information of the header.
     *     @type \Google\Transit\Realtime\TranslatedString $tts_header_text
     *           Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *     @type \Google\Transit\Realtime\TranslatedString $tts_description_text
     *           Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *     @type int $severity_level
     *     @type \Google\Transit\Realtime\TranslatedImage $image
     *           TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     *           The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
     *     @type \Google\Transit\Realtime\TranslatedString $image_alternative_text
     *           Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     *           or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     *     @type \Google\Transit\Realtime\TranslatedString $cause_detail
     *           Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type \Google\Transit\Realtime\TranslatedString $effect_detail
     *           Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * Should not be used - for backwards-compatibility only.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange active_period = 1 [deprecated = true];</code>
     * @return RepeatedField<\Google\Transit\Realtime\TimeRange>
     * @deprecated
     */
    public function getActivePeriod()
    {
        if (count($this->active_period) !== 0) {
            @trigger_error('active_period is deprecated.', E_USER_DEPRECATED);
        }
        return $this->active_period;
    }

    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * Should not be used - for backwards-compatibility only.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange active_period = 1 [deprecated = true];</code>
     * @param \Google\Transit\Realtime\TimeRange[] $var
     * @return $this
     * @deprecated
     */
    public function setActivePeriod($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TimeRange::class);
        if (count($arr) !== 0) {
            @trigger_error('active_period is deprecated.', E_USER_DEPRECATED);
        }
        $this->active_period = $arr;

        return $this;
    }

    /**
     * Time when the alert should be shown to the user strictly for informative reasons.
     * If missing, the consuming application can decide when it's appropriate to be shown.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange communication_period = 2;</code>
     * @return RepeatedField<\Google\Transit\Realtime\TimeRange>
     */
    public function getCommunicationPeriod()
    {
        return $this->communication_period;
    }

    /**
     * Time when the alert should be shown to the user strictly for informative reasons.
     * If missing, the consuming application can decide when it's appropriate to be shown.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange communication_period = 2;</code>
     * @param \Google\Transit\Realtime\TimeRange[] $var
     * @return $this
     */
    public function setCommunicationPeriod($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TimeRange::class);
        $this->communication_period = $arr;

        return $this;
    }

    /**
     * Time when the services are affected by the alert. If communication_period is specified,
     * every time interval in impact_period must be fully contained within at least
     * one time interval of communication_period.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange impact_period = 3;</code>
     * @return RepeatedField<\Google\Transit\Realtime\TimeRange>
     */
    public function getImpactPeriod()
    {
        return $this->impact_period;
    }

    /**
     * Time when the services are affected by the alert. If communication_period is specified,
     * every time interval in impact_period must be fully contained within at least
     * one time interval of communication_period.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TimeRange impact_period = 3;</code>
     * @param \Google\Transit\Realtime\TimeRange[] $var
     * @return $this
     */
    public function setImpactPeriod($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TimeRange::class);
        $this->impact_period = $arr;

        return $this;
    }

    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     * @return RepeatedField<\Google\Transit\Realtime\EntitySelector>
     */
    public function getInformedEntity()
    {
        return $this->informed_entity;
    }

    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     * @param \Google\Transit\Realtime\EntitySelector[] $var
     * @return $this
     */
    public function setInformedEntity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\EntitySelector::class);
        $this->informed_entity = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Cause cause = 6;</code>
     * @return int
     */
    public function getCause()
    {
        return isset($this->cause) ? $this->cause : 0;
    }

    public function hasCause()
    {
        return isset($this->cause);
    }

    public function clearCause()
    {
        unset($this->cause);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Cause cause = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCause($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\Cause::class);
        $this->cause = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Effect effect = 7;</code>
     * @return int
     */
    public function getEffect()
    {
        return isset($this->effect) ? $this->effect : 0;
    }

    public function hasEffect()
    {
        return isset($this->effect);
    }

    public function clearEffect()
    {
        unset($this->effect);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.Effect effect = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEffect($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\Effect::class);
        $this->effect = $var;

        return $this;
    }

    /**
     * The URL which provides additional information about the alert.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString url = 8;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getUrl()
    {
        return $this->url;
    }

    public function hasUrl()
    {
        return isset($this->url);
    }

    public function clearUrl()
    {
        unset($this->url);
    }

    /**
     * The URL which provides additional information about the alert.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString url = 8;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->url = $var;

        return $this;
    }

    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getHeaderText()
    {
        return $this->header_text;
    }

    public function hasHeaderText()
    {
        return isset($this->header_text);
    }

    public function clearHeaderText()
    {
        unset($this->header_text);
    }

    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setHeaderText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->header_text = $var;

        return $this;
    }

    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getDescriptionText()
    {
        return $this->description_text;
    }

    public function hasDescriptionText()
    {
        return isset($this->description_text);
    }

    public function clearDescriptionText()
    {
        unset($this->description_text);
    }

    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setDescriptionText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->description_text = $var;

        return $this;
    }

    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getTtsHeaderText()
    {
        return $this->tts_header_text;
    }

    public function hasTtsHeaderText()
    {
        return isset($this->tts_header_text);
    }

    public function clearTtsHeaderText()
    {
        unset($this->tts_header_text);
    }

    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsHeaderText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->tts_header_text = $var;

        return $this;
    }

    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getTtsDescriptionText()
    {
        return $this->tts_description_text;
    }

    public function hasTtsDescriptionText()
    {
        return isset($this->tts_description_text);
    }

    public function clearTtsDescriptionText()
    {
        unset($this->tts_description_text);
    }

    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsDescriptionText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->tts_description_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.SeverityLevel severity_level = 14;</code>
     * @return int
     */
    public function getSeverityLevel()
    {
        return isset($this->severity_level) ? $this->severity_level : 0;
    }

    public function hasSeverityLevel()
    {
        return isset($this->severity_level);
    }

    public function clearSeverityLevel()
    {
        unset($this->severity_level);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert.SeverityLevel severity_level = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setSeverityLevel($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\SeverityLevel::class);
        $this->severity_level = $var;

        return $this;
    }

    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedImage image = 15;</code>
     * @return \Google\Transit\Realtime\TranslatedImage|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedImage image = 15;</code>
     * @param \Google\Transit\Realtime\TranslatedImage $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedImage::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getImageAlternativeText()
    {
        return $this->image_alternative_text;
    }

    public function hasImageAlternativeText()
    {
        return isset($this->image_alternative_text);
    }

    public function clearImageAlternativeText()
    {
        unset($this->image_alternative_text);
    }

    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setImageAlternativeText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->image_alternative_text = $var;

        return $this;
    }

    /**
     * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getCauseDetail()
    {
        return $this->cause_detail;
    }

    public function hasCauseDetail()
    {
        return isset($this->cause_detail);
    }

    public function clearCauseDetail()
    {
        unset($this->cause_detail);
    }

    /**
     * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setCauseDetail($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->cause_detail = $var;

        return $this;
    }

    /**
     * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getEffectDetail()
    {
        return $this->effect_detail;
    }

    public function hasEffectDetail()
    {
        return isset($this->effect_detail);
    }

    public function clearEffectDetail()
    {
        unset($this->effect_detail);
    }

    /**
     * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setEffectDetail($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->effect_detail = $var;

        return $this;
    }

}

