<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A definition (or update) of an entity in the transit feed.
 *
 * Generated from protobuf message <code>transit_realtime.FeedEntity</code>
 */
class FeedEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     */
    protected $id = null;
    /**
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     *
     * Generated from protobuf field <code>optional bool is_deleted = 2;</code>
     */
    protected $is_deleted = null;
    /**
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    protected $trip_update = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    protected $alert = null;
    /**
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.Shape shape = 6;</code>
     */
    protected $shape = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop stop = 7;</code>
     */
    protected $stop = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripModifications trip_modifications = 8;</code>
     */
    protected $trip_modifications = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           The ids are used only to provide incrementality support. The id should be
     *           unique within a FeedMessage. Consequent FeedMessages may contain
     *           FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     *           FeedEntity with some id will replace the old FeedEntity with the same id
     *           (or delete it - see is_deleted below).
     *           The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     *           feed must be specified by explicit selectors (see EntitySelector below for
     *           more info).
     *     @type bool $is_deleted
     *           Whether this entity is to be deleted. Relevant only for incremental
     *           fetches.
     *     @type \Google\Transit\Realtime\TripUpdate $trip_update
     *           Data about the entity itself. Exactly one of the following fields must be
     *           present (unless the entity is being deleted).
     *     @type \Google\Transit\Realtime\VehiclePosition $vehicle
     *     @type \Google\Transit\Realtime\Alert $alert
     *     @type \Google\Transit\Realtime\Shape $shape
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type \Google\Transit\Realtime\Stop $stop
     *     @type \Google\Transit\Realtime\TripModifications $trip_modifications
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : '';
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     *
     * Generated from protobuf field <code>optional bool is_deleted = 2;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return isset($this->is_deleted) ? $this->is_deleted : false;
    }

    public function hasIsDeleted()
    {
        return isset($this->is_deleted);
    }

    public function clearIsDeleted()
    {
        unset($this->is_deleted);
    }

    /**
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     *
     * Generated from protobuf field <code>optional bool is_deleted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->is_deleted = $var;

        return $this;
    }

    /**
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     * @return \Google\Transit\Realtime\TripUpdate|null
     */
    public function getTripUpdate()
    {
        return $this->trip_update;
    }

    public function hasTripUpdate()
    {
        return isset($this->trip_update);
    }

    public function clearTripUpdate()
    {
        unset($this->trip_update);
    }

    /**
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     * @param \Google\Transit\Realtime\TripUpdate $var
     * @return $this
     */
    public function setTripUpdate($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TripUpdate::class);
        $this->trip_update = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     * @return \Google\Transit\Realtime\VehiclePosition|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     * @param \Google\Transit\Realtime\VehiclePosition $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\VehiclePosition::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert alert = 5;</code>
     * @return \Google\Transit\Realtime\Alert|null
     */
    public function getAlert()
    {
        return $this->alert;
    }

    public function hasAlert()
    {
        return isset($this->alert);
    }

    public function clearAlert()
    {
        unset($this->alert);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Alert alert = 5;</code>
     * @param \Google\Transit\Realtime\Alert $var
     * @return $this
     */
    public function setAlert($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\Alert::class);
        $this->alert = $var;

        return $this;
    }

    /**
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.Shape shape = 6;</code>
     * @return \Google\Transit\Realtime\Shape|null
     */
    public function getShape()
    {
        return $this->shape;
    }

    public function hasShape()
    {
        return isset($this->shape);
    }

    public function clearShape()
    {
        unset($this->shape);
    }

    /**
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.Shape shape = 6;</code>
     * @param \Google\Transit\Realtime\Shape $var
     * @return $this
     */
    public function setShape($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\Shape::class);
        $this->shape = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop stop = 7;</code>
     * @return \Google\Transit\Realtime\Stop|null
     */
    public function getStop()
    {
        return $this->stop;
    }

    public function hasStop()
    {
        return isset($this->stop);
    }

    public function clearStop()
    {
        unset($this->stop);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop stop = 7;</code>
     * @param \Google\Transit\Realtime\Stop $var
     * @return $this
     */
    public function setStop($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\Stop::class);
        $this->stop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripModifications trip_modifications = 8;</code>
     * @return \Google\Transit\Realtime\TripModifications|null
     */
    public function getTripModifications()
    {
        return $this->trip_modifications;
    }

    public function hasTripModifications()
    {
        return isset($this->trip_modifications);
    }

    public function clearTripModifications()
    {
        unset($this->trip_modifications);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripModifications trip_modifications = 8;</code>
     * @param \Google\Transit\Realtime\TripModifications $var
     * @return $this
     */
    public function setTripModifications($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TripModifications::class);
        $this->trip_modifications = $var;

        return $this;
    }

}

