<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An internationalized image containing per-language versions of a URL linking to an image
 * along with meta information
 * Only one of the images from a message will be retained by consumers. The resolution proceeds
 * as follows:
 * 1. If the UI language matches the language code of a translation,
 *    the first matching translation is picked.
 * 2. If a default UI language (e.g., English) matches the language code of a
 *    translation, the first matching translation is picked.
 * 3. If some translation has an unspecified language code, that translation is
 *    picked.
 *
 * Generated from protobuf message <code>transit_realtime.TranslatedImage</code>
 */
class TranslatedImage extends \Google\Protobuf\Internal\Message
{
    /**
     * At least one localized image must be provided.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    private $localized_image;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Transit\Realtime\TranslatedImage\LocalizedImage[] $localized_image
     *           At least one localized image must be provided.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * At least one localized image must be provided.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     * @return RepeatedField<\Google\Transit\Realtime\TranslatedImage\LocalizedImage>
     */
    public function getLocalizedImage()
    {
        return $this->localized_image;
    }

    /**
     * At least one localized image must be provided.
     *
     * Generated from protobuf field <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     * @param \Google\Transit\Realtime\TranslatedImage\LocalizedImage[] $var
     * @return $this
     */
    public function setLocalizedImage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TranslatedImage\LocalizedImage::class);
        $this->localized_image = $arr;

        return $this;
    }

}

